/* auto-generated by gensrv_java from /homes/timn/ros/local/rosspawn/srv/ListLoaded.srv.  Do not edit! */
package ros.pkg.rosspawn.srv;

import java.nio.ByteBuffer;

public class ListLoaded extends ros.communication.Service<ListLoaded.Request, ListLoaded.Response> 
{

public static String __s_getDataType() { return "rosspawn/ListLoaded"; }
public static String __s_getMD5Sum() { return "3d07bfda1268b4f76b16b7ba8a82665d"; }

public String getDataType() { return ListLoaded.__s_getDataType(); }
public String getMD5Sum() { return ListLoaded.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{


  public Request() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "rosspawn/ListLoadedRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("3d07bfda1268b4f76b16b7ba8a82665d"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("rosspawn/ListLoaded"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
  }
  public void deserialize(ByteBuffer bb)  {
  }
}

public static class Response extends ros.communication.Message
{

  public java.lang.String[] nodes;

  public Response() {
 super();
  nodes = new java.lang.String[0];

  }
  public static java.lang.String __s_getDataType() { return "rosspawn/ListLoadedResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string[] nodes\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("3d07bfda1268b4f76b16b7ba8a82665d"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("rosspawn/ListLoaded"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
      nodes =  (java.lang.String[])(clone.nodes.clone());
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("nodes", "java.lang.String[]");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    nodes = __m2.nodes;
    }

  int calc_nodes_array_serialization_len() {
    int l = 0;
    for (int i = 0; i < nodes.length; i++) 
      l += 4 + nodes[i].length();
    return l;
  }
  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + calc_nodes_array_serialization_len(); // nodes
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt(nodes.length);
    for (java.lang.String x : nodes)
      Serialization.writeString(bb, x);
  }
  public void deserialize(ByteBuffer bb)  {
     int nodes_len = bb.getInt();
    nodes = new java.lang.String[nodes_len];
    for(int i = 0; i < nodes_len; i++)
      nodes[i] = Serialization.readString(bb);
  }
}

public ListLoaded.Request createRequest() { return new ListLoaded.Request(); }public ListLoaded.Response createResponse() { return new ListLoaded.Response(); }}

