/* auto-generated by gensrv_java from /homes/timn/ros/local/rosspawn/srv/StartNode.srv.  Do not edit! */
package ros.pkg.rosspawn.srv;

import java.nio.ByteBuffer;

public class StartNode extends ros.communication.Service<StartNode.Request, StartNode.Response> 
{

public static String __s_getDataType() { return "rosspawn/StartNode"; }
public static String __s_getMD5Sum() { return "014964366824ce564884dfdaff1faba6"; }

public String getDataType() { return StartNode.__s_getDataType(); }
public String getMD5Sum() { return StartNode.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public java.lang.String node_file_name;

  public Request() {
 super();
    node_file_name = new java.lang.String();

  }
  public static java.lang.String __s_getDataType() { return "rosspawn/StartNodeRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string node_file_name\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("014964366824ce564884dfdaff1faba6"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("rosspawn/StartNode"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("node_file_name", "java.lang.String");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    node_file_name = __m2.node_file_name;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + node_file_name.length(); // node_file_name
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, node_file_name);
  }
  public void deserialize(ByteBuffer bb)  {
    node_file_name = Serialization.readString(bb);
  }
}

public static class Response extends ros.communication.Message
{


  public Response() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "rosspawn/StartNodeResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("014964366824ce564884dfdaff1faba6"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("rosspawn/StartNode"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
  }
  public void deserialize(ByteBuffer bb)  {
  }
}

public StartNode.Request createRequest() { return new StartNode.Request(); }public StartNode.Response createResponse() { return new StartNode.Response(); }}

